### ISSUE TITLE
RedisClient error

### ISSUE THREAD

**Issue by mertcakmak2** [bsm/redislock#49] opened 2022-10-06 13:22 UTC
I try your example code but doesn't working.

**Go version:** go1.19.1 windows/amd64
**redislock version in go mod file:** github.com/bsm/redislock v0.8.0
**redis version in go mod file:** github.com/go-redis/redis/v9 v9.0.0-beta.3

I have error as below.

redislock.go:149:31: cannot use l.client.client (variable of type RedisClient) as type redis.Scripter in argument to 
luaPTTL.Run:
        RedisClient does not implement redis.Scripter (missing EvalRO method)
C:\Users\P1608\go\pkg\mod\github.com\bsm\redislock@v0.8.0\redislock.go:166:37: cannot use l.client.client (variable of type RedisClient) as type redis.Scripter in argument to 
luaRefresh.Run:
        RedisClient does not implement redis.Scripter (missing EvalRO method)
C:\Users\P1608\go\pkg\mod\github.com\bsm\redislock@v0.8.0\redislock.go:178:34: cannot use l.client.client (variable of type RedisClient) as type redis.Scripter in argument to 
luaRelease.Run:
        RedisClient does not implement redis.Scripter (missing EvalRO method)

**Comment by dim** [comment] 2022-10-07 08:02
Duplicate of https://github.com/bsm/redislock/issues/46

**Comment by dim** [comment] 2022-10-07 08:07
Apologies, I see it now, fixed in https://github.com/bsm/redislock/pull/50

**Comment by dim** [comment] 2022-10-07 08:14
Pushed new release, thanks for reporting the issue

**Closed by dim** 2022-10-07 08:14 UTC

**Comment by nmfzone** [comment] 2022-12-10 14:20
And now redislock drop support for Redis v8?

**Comment by dim** [comment] 2022-12-12 08:41
@nmfzone the v8 branch of https://github.com/go-redis/redis is not being maintained by its author either but you can always pin your go.mod to `0.7.x` version of this lib?

**Comment by nmfzone** [comment] 2022-12-12 15:48
Yeah, I know. Well, if you can keep support for redis v8 then it's good, right? Since there is a lot users who still using v8, especially in production. #justmy2cent

**Comment by dim** [comment] 2022-12-12 16:54
Sure, we can backport new features and release them as 0.7.x tags. Is there anything you are missing right now?

**Comment by dim** [comment] 2022-12-12 17:02
Here you go, here's a new branch https://github.com/bsm/redislock/tree/0.7
